export default {
    QUERY_SET_OBJECT:'QUERY_SET_OBJECT',

    APP_SET_COLLECTION:'APP_SET_COLLECTION',
    APP_SET_CONFIG_QUERIES:'APP_SET_CONFIG_QUERIES',
    APP_SET_QUERY_VALUES:'APP_SET_QUERY_VALUES',
    APP_SET_QUERY_TYPE:'APP_SET_QUERY_TYPE',
    APP_SET_QUERY_COLLECTION_STATE:'APP_SET_QUERY_COLLECTION_STATE',

    STAGE_SET_QUERY_COLLECTION_STATE:'STAGE_SET_QUERY_COLLECTION_STATE',
    
    FORMLINE_SET_QUERY_COLLECTION_STATE: 'FORMLINE_SET_QUERY_COLLECTION_STATE',

    CURSOR_INSERT_CURSOR:'CURSOR_INSERT_CURSOR',

    CONNECTOR_SET_DBCOLLECTIONS:'CONNECTOR_SET_DBCOLLECTIONS',
    CONNECTOR_SET_MESSAGE:'CONNECTOR_SET_MESSAGE',
    CONNECTOR_SET_ISCONNECTED: 'CONNECTOR_SET_ISCONNECTED',
    CONNECTOR_SET_COLLECTION:'CONNECTOR_SET_COLLECTION',
    CONNECTOR_SET_CONNECTION_PARAMS: 'CONNECTOR_SET_CONNECTION_PARAMS',

    INTERROGATOR_SET_COLLECTION: 'INTERROGATOR_SET_COLLECTION',
    INTERROGATOR_SET_CONFIG_QUERIES: 'INTERROGATOR_SET_CONFIG_QUERIES',
    INTERROGATOR_SET_QUERY_VALUES: 'INTERROGATOR_SET_QUERY_VALUES',
    INTERROGATOR_SET_QUERY_TYPE: 'INTERROGATOR_SET_QUERY_TYPE',
    INTERROGATOR_SET_QUERY_COLLECTION_STATE: 'INTERROGATOR_SET_QUERY_COLLECTION_STATE',
    INTERROGATOR_SET_RESULTS: 'INTERROGATOR_SET_RESULTS',
    INTERROGATOR_SET_QUERYMESSAGE:'INTERROGATOR_SET_QUERYMESSAGE',

    LOGINIFRAME_RECORD_USER_DETAILS: 'LOGINIFRAME_RECORD_USER_DETAILS',
    LOGINIFRAME_LOGIN_USER: 'LOGINIFRAME_LOGIN_USER',
    LOGINIFRAME_RECORD_USER_OBJECT: 'LOGINIFRAME_RECORD_USER_OBJECT',
    LOGINIFRAME_SET_CONNECTION_PARAMS: 'LOGINIFRAME_SET_CONNECTION_PARAMS',
    LOGINIFRAME_SET_DBCOLLECTIONS: 'LOGINIFRAME_SET_DBCOLLECTIONS',
    LOGINIFRAME_SET_ISCONNECTED: 'LOGINIFRAME_SET_ISCONNECTED',
    
    TOOLS_APPLY_LOADED_STATE:'TOOLS_APPLY_LOADED_STATE'
}
