export default {

    SET_CONFIG_QUERIES: 'SET_CONFIG_QUERIES',

    SET_COLLECTION: 'SET_COLLECTION',
    SET_QUERY_TYPE: 'SET_QUERY_TYPE',
    SET_QUERY_VALUES: 'SET_QUERY_VALUES',
    SET_QUERY_COLLECTION_STATE: 'SET_QUERY_COLLECTION_STATE',
    INSERT_CURSOR: 'INSERT_CURSOR',

    SET_DBCOLLECTIONS: 'SET_DBCOLLECTIONS',
    SET_ISCONNECTED: 'SET_ISCONNECTED',
    SET_CONNECTION_PARAMS: 'SET_CONNECTION_PARAMS',

    SET_RESULTS: 'SET_RESULTS',
    SET_QUERYMESSAGE: 'SET_QUERYMESSAGE',

    RECORD_USER_DETAILS: 'RECORD_USER_DETAILS',
    LOGIN_USER: 'LOGIN_USER',
    RECORD_USER_OBJECT: 'RECORD_USER_OBJECT',
    APPLY_LOADED_STATE: 'APPLY_LOADED_STATE'
}
